Add bookings
aperanto-lefko/java-shareit pull request #3
Opened 2024-12-27 11:13 UTC by aperanto-lefko

Выполнение задания согласно ТЗ 15 спринта

2024-12-29 11:17 UTC, EugeneLenkevich requested changes
Привет, Виктория ! Спасибо за PR.


В целом все верно, есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста
И, в первую очередь, посмотри на обработку исключений, будь то бы ее в первую очередь до ума довести 

С Наступающим!

2024-12-29 11:17 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/error_handler/ErrorHandler.java
> +        String fieldName = Objects.requireNonNull(e.getBindingResult().getFieldError()).getField(); //получение поля, которое вызвало ошибку
Стремление писать универсальный код понятно, но тут это приводит к переусложнению.
Для каждой ситуации лучше завести свой тип исключения чтобы сразу можно было идентифицировать конкретную ситуацию. И обрабатывать так же каждый такой тип отдельно. Ну и плюс добавить дополнительный обработчик для всех остальных типов исключений, который будет возвращать 500ую ошибку

Это нам поможет избавиться вот от такого условия
![image](https://github.com/user-attachments/assets/ea1e3936-7c20-4b01-a65b-dec4b845d1a8)

2024-12-29 11:17 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@Data
`@Data`

С этой аннотацией надо поаккуратней. Она генерирует equals и hashCode на основании всех полей. 
Однако, сущность - это не просто объект, это представление строки таблицы базы данных, а строку таблицы однозначно определяет ее идентификатор, и потому, соотвественно, для сущностей equals и hashCode стоит определять на основе id (первичного ключа). 

Остальные поля, при этом, могут вообще быть разными, то есть могут существовать разные версии одного и того же объекта, но как это разруливатеся - это уже отдельная история.
 
Плюс еще некоторые поля могут быть ленивыми коллекциями и в момент обращения бдут генерироваться sql-запросы, которые и не нужны в данный момент

Т.е. лучше или переопределить руками или указать через аннотации как генерировать эти методы :)

2024-12-29 11:17 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                .filter(Item::getAvailable)
.filter(Item::getAvailable)

А зачем тут дополнительный фильтр, лучше ненужные данные из БД вовсе не доставать, то есть делать фильтрацию на уровне sql-запроса

2024-12-29 11:17 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                    .orElseThrow(() -> new BadRequestException("Текущее бронирование для вещи с id " + id + " не найдено"));
Не стоит кидать и тут же перехватывать исключение, это слишком сложно и избыточно. Тут наверно можно сделать .orElse(null)

И в других местах тоже посмотри нет ли такого же

2024-12-29 11:17 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        User user = userRepository.findById(request.getId()).get();
userRepository.findById(request.getId()).get();

Вот, уже другой способ получения сущности :)

Давай вот как то так попробуем
https://stackoverflow.com/questions/7471625/fastest-check-if-row-exists-in-postgresql

Или так
https://stackoverflow.com/questions/30392129/spring-data-jpa-and-exists-query

2025-01-01 09:41 UTC, aperanto-lefko commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findByBookerIdOrItemOwnerIdAndStartBeforeAndEndAfterOrderByStartDesc(Long bookerId,  //текущие бронирования
done

2025-01-01 21:03 UTC, aperanto-lefko commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                    .orElseThrow(() -> new BadRequestException("Текущее бронирование для вещи с id " + id + " не найдено"));
done

2025-01-01 21:04 UTC, aperanto-lefko commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private final ItemRepository itemRepository;
Не везде получается сервисами заменить-получаются циклические зависимости

2025-01-01 21:20 UTC, aperanto-lefko commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new BadRequestException("Дата начала и конца бронирования не может совпадать");
done

2025-01-01 21:34 UTC, aperanto-lefko commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    public BookingDto createApprove(Long userId, Long bookingId, String approved) {
done

2025-01-01 21:47 UTC, aperanto-lefko commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    public List<BookingDto> searchBookingsWithState(Long userId, String state) {
done

2025-01-01 21:47 UTC, aperanto-lefko commented on src/main/java/ru/practicum/shareit/error_handler/ErrorHandler.java
> +        String fieldName = Objects.requireNonNull(e.getBindingResult().getFieldError()).getField(); //получение поля, которое вызвало ошибку
done

2025-01-01 22:03 UTC, aperanto-lefko commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@Data
done

2025-01-01 22:23 UTC, aperanto-lefko commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                .filter(Item::getAvailable)
done

2025-01-02 09:48 UTC, aperanto-lefko commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        User user = userRepository.findById(request.getId()).get();
в ссылке приводится пример проверки на наличие, а мне нужна сама сущность, чтобы проверить email и обновить её. Заменила на один метод

2025-01-02 13:37 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/error_handler/ErrorHandler.java
> +        String fieldName = Objects.requireNonNull(e.getBindingResult().getFieldError()).getField(); //получение поля, которое вызвало ошибку
А в каком порядке обработчики объявляются?

2025-01-02 13:40 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        User user = userRepository.findById(request.getId()).get();
Имел в виду что вот эту проверку, на уникальность email, можно сделать предварительно

![image](https://github.com/user-attachments/assets/86435885-9ced-40b0-9e4a-c9eb683bd1c8)

2025-01-02 13:50 UTC, EugeneLenkevich approved these changes
Привет, спасибо за исправления и в Новым Годом!

Ну в целом все верно, ну в целом критические моменты поправлены, что то осталось, но это уже не критично. То что получилась стратегия - круто, этот паттерн любят на собеседованиях. В общем, поехали дальше

2025-01-02 13:50 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/exception/InvalidBookingIdException.java
> +public class InvalidBookingIdException extends RuntimeException {
extends Exception

Эти исключения лучше делать проверяемыми, они есть в бизнес-процессе, таким образом мы на уровне компилятора заявляем о наличии таких ситуаций - вышестоящий код должен будет их или обработать или прокинуть дальше. Непроверяемое исключение - на то и непроверяемое потому что непредсказуемое, обычно оно означает ошибку в самой логике

2025-01-02 20:57 UTC, merged